const actions = {
  LOGGED_IN: "LOGGED_IN",
  LOGGED_OUT: "LOGGED_OUT",
  LOADING: "LOADING",
  SET_ERROR: "SET_ERROR",
  UNSET_ERROR: "UNSET_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
  CREATE_USER: "CREATE_USER",
  CU_SET_RESPONSE: 'CREATE_USER_SET_MESSAGE',
  CU_LOADING: 'CU_LOADING',
  GAME_SOCKET_CREATE: 'GAME_SOCKET_CREATE',
  GAME_CONNECTED: 'GAME_CONNECTED',
  GAME_UPDATE_STATE: 'GAME_UPDATE_STATE',
  INVITE: 'INVITE',
  INVITE_MESSAGE: 'INVITE_MESSAGE',
};

export default actions;
