const actions = {
  LOGGED_IN: "LOGGED_IN",
  LOGGED_OUT: "LOGGED_OUT",
  LOADING: "LOADING",
  SET_ERROR: "SET_ERROR",
  UNSET_ERROR: "UNSET_ERROR",
  SET_MESSAGE: "SET_MESSAGE",
  CREATE_USER: "CREATE_USER",
  CU_SET_RESPONSE: 'CREATE_USER_SET_MESSAGE',
  CU_LOADING: 'CU_LOADING',
};

export default actions;
